kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-agent-cluster-admin
subjects:
  - kind: ServiceAccount
    name: argocd-agent-sa
    namespace: argocd-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
