apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  argoCDAgent:
    agent:
      allowedNamespaces:
        - "*-argocd"
      enabled: true
      env:
        - name: ARGOCD_AGENT_LABEL_SELECTOR
          value: "argocd-agent=true"
      creds: mtls:CN=([^,]+)
      client:
        enableCompression: true
        enableWebSocket: false
        mode: managed
        principalServerAddress: argocd-agent-principal-argocd.apps.hub.ocplab.com
      destinationBasedMapping:
        enabled: true
        createNamespace: true
      tls:
        rootCASecretName: argocd-agent-ca
        secretName: argocd-agent-client-tls
  server:
    enabled: false
  sourceNamespaces:
    - "*-argocd"
