apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    argocd-agent: "true"
  name: cluster-config
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    name: '*'
  sourceRepos:
  - '*'
  roles:
  - name: cluster-admins
    policies:
    - p, proj:bootstrap:admin, applications, *, bootstrap/*, allow
    groups:
    - "cluster-admins"
