apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |
      - op: replace
        path: /spec/storage
        value:
          empryDir: {}
      - op: replace
        path: /spec/replicas
        value: "0"
    target:
      kind: Config
