apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app: noobaa
  name: noobaa-default-backing-store
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 100Gi
    storageClass: nfs-csi
  type: pv-pool
