apiVersion: v1
kind: Secret
metadata:
  annotations:
    baseDomain: hub.ocplab.com
    subdomain: apps.hub.ocplab.com
    clusterID: sss
    infrastructureID: sss
    targetRevision: HEAD
  name: hub-prod-local
  namespace: argocd
  labels:
    app.kubernetes.io/name: hub-prod-local
    argocd.argoproj.io/secret-type: cluster
    env: prod
    region: local
    type: hub
stringData:
  name: hub-prod-local
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
