apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

components:
- ../../components/alert-rules
- ../../components/action-compliance
- ../../components/extension-assistant-lightspeed
- ../../components/oidc-keycloak-ocplab
- ../../components/agent-principal
- ../../components/disable-cluster-roles
- ../../components/policy-generator
- ../../components/health-application
- ../../components/health-build
- ../../components/health-imagestream
- ../../components/health-ingress
- ../../components/health-multiclusterhub
- ../../components/health-pvc
- ../../components/health-policy
- ../../components/health-rolloutmanager
- ../../components/health-stackrox
- ../../components/health-subscription
- ../../components/policy-generator
- ../../components/disable-cluster-roles

resources:
- ../../base
- application-controller-cluster-admin-role.yaml
- hub-prod-local-secret.yaml
- appproject.yaml
- server-clusterrole.yaml
# AppSets in Any Namespace require more permissions then what operator gives
# since it is not supported yet. Commented out for now as we switch to destination
# based routing but might re-use if I decide to have tenants share the same instance
# - appset-in-any-namespace-clusterrole.yaml

patches:
- patch: |
    - op: add
      path: /metadata/labels/cluster-secrets
      value: "true"
  target:
    kind: Namespace
    name: argocd
