apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: openshift-config
  labels:
    clusterSettings: "true"
data:
  baseDomain: hub.ocplab.com
  subdomain: apps.hub.ocplab.com
  clusterID: xxxx
  infrastructureID: xxxx
