apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: pipelines-scc-user-namespaces
priority: null
allowPrivilegeEscalation: true
allowedCapabilities:
  - SETUID
  - SETGID
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 65534
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    type: container_engine_t
supplementalGroups:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 65534
userNamespaceLevel: RequirePodLevel
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-user-namespaces
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - pipeline-user-namespaces
