apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  promoter:
    apiserver:
      enabled: true
      tls:
        caSecretKey: tls.key
        caSecretName: argocd-promoter-apiserver-tls
        certSecretName: argocd-promoter-apiserver-tls
    argoCDUIExtensionEnabled: false
    enabled: true
    webhook:
      enabled: true
