apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: argocd-agent-jwt-signing
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster
  target:
    name: argocd-agent-jwt-signing
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  dataFrom:
  - extract:
      key: ARGOCD_AGENT_JWT_SIGNING_SECRET
