apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster
  target:
    name: credentials
  data:
    - secretKey: apitoken
      remoteRef:
        key: OLS_API_TOKEN
