apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

components:
- ../../components/extension-assistant-lightspeed
- ../../components/health-application
- ../../components/health-pvc
- ../../components/health-subscription

resources:
- ../../base

patches:
  - patch: |
      - op: replace
        path: /spec/provider/kubernetes/remoteNamespace
        value: demo-gitops
    target:
      kind: SecretStore
      name: k8s-store
  - patch: |
      - op: replace
        path: /subjects/0/namespace
        value: openshift-gitops
      - op: replace
        path: /metadata/name
        value: lightspeed-operator-query-access-openshift-gitops
    target:
      kind: ClusterRoleBinding
      name: lightspeed-operator-query-access-argocd
