apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trusted-profile-analyzer

resources:
- namespace.yaml
- obc.yaml
- oidc-es.yaml
- postgresql-es.yaml
- postgresql.yaml

helmCharts:
- name: redhat-trusted-profile-analyzer
  version: 1.2.6
  repo: https://charts.openshift.io
  namespace: trusted-profile-analyzer
  releaseName: trusted-profile-analyzer
  valuesFile: values.yaml
