apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  applicationSet:
    enabled: true
  argoCDAgent:
    principal:
      destinationBasedMapping: true
      enabled: true
      jwt:
        secretName: argocd-agent-jwt-signing
      auth: mtls:CN=([^,]+)
      image: quay.io/gnunn/argocd-agent:namespace-mapping-fix
  controller:
    enabled: false
