apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-agent-principal-tls
spec:
  dnsNames:
  - argocd-agent-principal-argocd.apps.hub.ocplab.com
  issuerRef:
    name: argocd-agent-ca
    kind: Issuer
  commonName: principal
  secretName: argocd-agent-principal-tls
  subject:
    organizationalUnits:
      - ocplab.com
