apiVersion: config.openshift.io/v1
kind: Console
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: cluster
spec:
  authentication:
    logoutRedirect: https://sso.ocplab.com/realms/ocplab/protocol/openid-connect/logout?client_id=openshift&post_logout_redirect_uri=https://console-openshift-console.apps.hub.ocplab.com
