apiVersion: secrets-management.openshift.io/v1alpha1
kind: SecretsManagementConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  name: cluster
spec:
  features:
    create:
      checkRBAC: true
      enabled: true
    delete:
      checkRBAC: true
      enabled: true
    edit:
      checkRBAC: true
      enabled: true
  operators:
    certManager:
      enabled: true
    externalSecrets:
      enabled: true
    secretsStoreCSI:
      enabled: false
  plugin:
    imagePullPolicy: IfNotPresent
    replicas: 1
    resources:
      limits: {}
      requests: {}
  rbac:
    createDefaultRoles: true
    rolePrefix: secrets-management
