apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: artifact-keeper
    repo: https://artifact-keeper.github.io/artifact-keeper-iac/
    version: 1.9.7
    releaseName: artifact-keeper
    namespace: artifact-keeper
    valuesFile: values.yaml
