apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-monitoring

resources:
- alertmanager-main-secret.yaml
- pending-csr-rule.yaml
- monitoring-role-binding.yaml
- service-account.yaml
- token-secret.yaml
