apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  applicationSet:
    enabled: true
    extraCommandArgs:
      - "--enable-progressive-syncs"
    sourceNamespaces:
      - "*-argocd"
  argoCDAgent:
    principal:
      destinationBasedMapping: true
      enabled: true
      env:
        - name: ARGOCD_PRINCIPAL_LABEL_SELECTOR
          value: "argocd-agent=true"
      namespace:
        allowedNamespaces:
          - "argocd"
          - "*-argocd"
      jwt:
        secretName: argocd-agent-jwt-signing
      auth: mtls:CN=([^,]+)
  server:
    env:
      - name: ARGOCD_REDIS_SERVER
        value: "argocd-agent-principal-redisproxy:6379"
  sourceNamespaces:
    - "*-argocd"
