apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  applicationSet:
    enabled: true
    extraCommandArgs:
      - "--enable-progressive-syncs"
  argoCDAgent:
    principal:
      destinationBasedMapping: true
      enabled: true
      namespace:
        allowedNamespaces:
          - "argocd"
          - "*-argocd"
      jwt:
        secretName: argocd-agent-jwt-signing
      auth: mtls:CN=([^,]+)
      #image: quay.io/gnunn/argocd-agent:namespace-mapping-fix
      image: quay.io/argoprojlabs/argocd-agent:v0.9.0
  controller:
    enabled: false
  sourceNamespaces:
    - "*-argocd"
