apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster
  target:
    name: google-secret
  data:
    - secretKey: clientSecret
      remoteRef:
        key: GOOGLE_SSO
