apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trusted-profile-analyzer

resources:
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
- obc.yaml
- oidc-es.yaml
- postgresql-es.yaml
- postgresql.yaml
- trusted-profile-analyzer.yaml
