object-templates-raw: |
  {{- $clusterEnv := "prod" }}
  {{- $version := "HEAD" }}
  {{- range $k,$v := (lookup "v1" "ConfigMap" "cluster-versions" "cluster-versions").data }}
    {{- if eq $clusterEnv $k }}
      ((- $version = $v))
    {{- end}}
  {{- end }}
  - complianceType: mustonlyhave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        annotations:
          baseDomain: '{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}'
          subdomain: '{{ (lookup "config.openshift.io/v1" "Ingress" "openshift-ingress" "cluster").spec.domain }}'
          clusterID: '{{ (lookup "config.openshift.io/v1" "ClusterVersion" "" "version").spec.clusterID }}'
          infrastructureID: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
          targetRevision: '{{ $version }}'
        name: hub-prod-local
        namespace: argocd
        labels:
          app.kubernetes.io/name: hub-prod-local
          argocd.argoproj.io/secret-type: cluster
          env: prod
          region: local
          type: hub
      stringData:
        name: hub-prod-local
        server: https://kubernetes.default.svc
        config: |
          {
            "tlsClientConfig": {
              "insecure": false
            }
          }
