apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: argocd-agent-registration
placementBindingDefaults:
  name: argocd-agent-registration
policyDefaults:
  complianceType: "mustonlyhave"
  # Need to keep cluster-secrets in a different manifest for reconciliation
  consolidateManifests: false
  namespace: acm-policies
  remediationAction: enforce
policies:
  - name: argocd-agent-registration
    description: Register Argo CD Agents on Control Plane
    manifests:
      - path: manifests/argocd-agent-register.yaml
    placement:
      placementName: argocd-agent-registration
  - name: argocd-agent-cluster-secret
    description: Argo CD Agent Cluster Secret on Control Plane
    manifests:
      - path: manifests/argocd-agent-cluster-secret.yaml
    placement:
      placementName: argocd-agent-registration
  - name: argocd-control-plane-secret
    description: Argo CD Control Plane Cluster Secret for Hybrid
    manifests:
      - path: manifests/argocd-control-plane-secret.yaml
    placement:
      placementName: argocd-agent-registration
