apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: tenants-token
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            key: token
            name: tenants-token
