---
object-templates-raw: |
  ## Example from Brian Jarvis: https://github.com/bry-tam/acm-policy-samples/blob/main/template-examples/snippets/managed_cluster_argo_agent/cluster-secret.yml
  ## look through all of the managed clusters, and find the onces where argo-agent should be running
  {{- range $mc := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "" "argocd-agent").items }}
    {{- $mc_name := $mc.metadata.name }}
    {{- $agent_name := (index $mc.metadata.labels "argocd-agent")}}
    {{- $cluster_info := dict }}

    ## set clusterID
    {{- $_ := set $cluster_info "cluster_id" (dig "clusterID" "" $mc.metadata.labels) }}

    ## set cluster info for status.clusterClaims
    {{- range $cc := $mc.status.clusterClaims }}
      {{- if eq $cc.name "apiserverurl.openshift.io" }}
        ## using the api address we can calculate the base domain and apps domain
        {{- $base_domain := $cc.value | replace "https://api." "" | replace ":6443" "" }}
        {{- $_ := set $cluster_info "base_domain" $base_domain }}
        {{- $_ := set $cluster_info "app_domain" (printf "apps.%s" $base_domain) }}
      {{- else if eq $cc.name "infrastructure.openshift.io" }}
        ## get the infrastructure id of the cluster
        {{- $_ := set $cluster_info "infra_id" ($cc.value | fromJson).infraName }}
      {{- end }}
    {{- end }}

  - complianceType: mustonlyhave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        annotations:
          clusterID: '{{ $cluster_info.cluster_id }}'
          infrastructureID: '{{ $cluster_info.infra_id }}'
          subdomain: '{{ $cluster_info.app_domain }}'
          baseDomain: '{{ $cluster_info.base_domain }}'
        name: {{ $agent_name }}-cluster
        namespace: argocd
        labels:
          argocd.argoproj.io/secret-type: cluster
          argocd-agent.argoproj-labs.io/agent-name: {{ $agent_name }}
      stringData:
        name: {{ $agent_name }}
        server: https://argocd-agent-principal-resource-proxy.argocd.svc.cluster.local:9090?agentName={{ $agent_name }}
        config: |
          {
            "tlsClientConfig": {
                "insecure": false,
                "certData": "{{ (fromSecret "argocd" (printf "argocd-principal-%s" $agent_name ) "tls.crt") }}",
                "keyData": "{{ (fromSecret "argocd" (printf "argocd-principal-%s" $agent_name ) "tls.key") }}",
                "caData": "{{ (fromSecret "argocd" (printf "argocd-principal-%s" $agent_name ) "ca.crt") }}"
            }
          }

  {{- end }}
