apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  extraConfig:
    application.sync.impersonation.enabled: "true"
    application.sync.impersonation.enforced: "false"
