apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - patch: |
      - op: add
        path: /metadata/labels/machineconfiguration.openshift.io~1role
        value: master
    target:
      kind: MachineConfig
      name: 99-networkmanager-wol
