apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- agent-redis-networkpolicy.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/argoCDAgent
        value:
          agent:
            enabled: true
            creds: mtls:CN=([^,]+)
            client:
              enableCompression: true
              enableWebSocket: false
              mode: managed
              principalServerAddress: argocd-agent-principal-argocd.apps.hub.ocplab.com
            tls:
              rootCASecretName: argocd-agent-ca
              secretName: argocd-agent-client-tls
      - op: add
        path: /spec/server/enabled
        value: false
    target:
      kind: ArgoCD
