apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  labels:
    cluster-name: hub-prod-local
  # Use finalizer to delete resources when Application is deleted
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/gnunn-gitops/cluster-config-v2
              revision: main
              files:
                - path: apps/**/overlays/all/config.json
                - path: apps/**/overlays/all/config.json
                - path: apps/**/overlays/hub/config.json
                - path: apps/**/overlays/hub-prod/config.json
                - path: apps/**/overlays/hub-prod-local/config.json
              values:
                name: '{{ ternary (index . "appName") (index .path.segments 1) (hasKey . "appName") }}'
                destinationNamespace: '{{ ternary (index . "namespace") (index .path.segments 1) (hasKey . "namespace") }}'
                group: '{{ ternary (index . "group") "other" (hasKey . "group") }}'
                serverSideApply: '{{ ternary (index . "serverSideApply") "false" (hasKey . "serverSideApply") }}'
          - clusters:
              selector:
                matchLabels:
                  argocd-agent.argoproj-labs.io/agent-name: hub-prod-local
                  argocd.argoproj.io/secret-type: cluster
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy/automated
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: group
              operator: In
              values:
                - core

        - matchExpressions:
            - key: name
              operator: In
              values:
                - config

        - matchExpressions:
            - key: name
              operator: In
              values:
                - operators

        - matchExpressions:
            - key: name
              operator: In
              values:
                - other
  template:
    metadata:
      name: 'hpl-{{ .values.name }}'
      labels:
        name: '{{ .values.name }}'
        cluster-name: '{{ .name }}'
        group: "{{ .group }}"
    spec:
      info:
        - name: "parameters"
          value: |
            {{ toPrettyJson . }}
      project: hub-prod-local
      source:
        repoURL: https://github.com/gnunn-gitops/cluster-config-v2
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        name: '{{ .name }}'
        namespace: '{{ .values.destinationNamespace }}'
      syncPolicy:
        automated:
          enabled: true
          selfHeal: true
  templatePatch: |
    {{- if eq .values.serverSideApply "true" }}
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
    {{- end }}
