apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: lab-server
spec:
  desiredState:
    interfaces:
    - name: enp7s0
      state: absent
      type: ethernet
    - name: enp8s0
      type: ethernet
      state: up
      dispatch:
        post-activation: |
          /usr/sbin/ethtool -s enp8s0 wol g
