apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: lab-server
spec:
  desiredState:
    interfaces:
    - name: enp7s0
      state: absent
      type: ethernet
      ipv4:
        dhcp: true
        enabled: true
        auto-dns: true
    - name: enp8s0
      type: ethernet
      state: up
      dispatch:
        post-activation: |
          /sbin/ethtool -s eth1 wol g
