apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: standalone
  namespace: argocd2
spec:
  argoServer:
    argoNamespace: argocd-standalone
    cluster: workload-prod-local
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: global
    namespace: argocd2
