apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: core-secrets
spec:
  clusterSets:
  - global
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: core-secret
          operator: Exists
