apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'csi-driver-nfs-anyuid'
subjects:
  - kind: ServiceAccount
    name: csi-nfs-controller-sa
    namespace: csi-driver-nfs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
