apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-networkmanager-wol
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W2Nvbm5lY3Rpb25dCmV0aGVybmV0Lndha2Utb24tbGFuPW1hZ2ljCg==
        mode: 420
        path: /etc/NetworkManager/conf.d/99-wol.conf
