apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-options: ServerSideApply=true,SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: Basic
  localClusterName: local-cluster
  overrides:
    components:
      - name: submariner-addon
        configOverrides: {}
        enabled: false
      - name: volsync
        enabled: false
        configOverrides: {}
      - configOverrides: {}
        enabled: true
        name: app-lifecycle
      - configOverrides: {}
        enabled: true
        name: cluster-lifecycle
      - configOverrides: {}
        enabled: true
        name: cluster-permission
      - configOverrides: {}
        enabled: true
        name: console
      - configOverrides: {}
        enabled: true
        name: grc
      - configOverrides: {}
        enabled: true
        name: insights
      - configOverrides: {}
        enabled: true
        name: multicluster-engine
      - configOverrides: {}
        enabled: true
        name: multicluster-observability
      - configOverrides: {}
        enabled: true
        name: search
      - configOverrides: {}
        enabled: false
        name: cluster-backup
      - configOverrides: {}
        enabled: false
        name: fine-grained-rbac-preview
      - configOverrides: {}
        enabled: false
        name: siteconfig
      - configOverrides: {}
        enabled: false
        name: cnv-mtv-integrations-preview
