apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: custom-worker-config
spec:
  # Use auto sizing for reserving space for system processes
  autoSizingReserved: true
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: custom-worker-config
  kubeletConfig:
    maxPods: 350
