apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster
  target:
    name: postgresql
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: RHTPA_POSTGRESQL
