apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      - op: add
        path: /spec/server/initContainers/-
        value:
          name: extension-gitops-promoter
          image: quay.io/argoprojlabs/quay.io/argoprojlabs/argocd-extension-installer:v0.0.8
          env:
            - name: EXTENSION_NAME
              value: gitops-promoter
            - name: EXTENSION_URL
              value: https://github.com/argoproj-labs/gitops-promoter/releases/download/v0.34.0/gitops-promoter-argocd-extension.tar.gz
            - name: EXTENSION_CHECKSUM_URL
              value: https://github.com/argoproj-labs/gitops-promoter/releases/download/v0.34.0/gitops-promoter_0.34.0_checksums.txt
          volumeMounts:
            - name: rollout-extensions
              mountPath: /tmp/extensions/
          securityContext:
            allowPrivilegeEscalation: false
    target:
      kind: ArgoCD
