apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: sensor-tls
  namespace: stackrox
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: cluster-push-secret
      kind: ClusterSecretStore
  selector:
    secret:
      name: sensor-tls
  data:
    - match:
        secretKey: ca.pem
        remoteRef:
          remoteKey: ACS_SENSOR_TLS_CA
    - match:
        secretKey: sensor-cert.pem
        remoteRef:
          remoteKey: ACS_SENSOR_TLS_CERT
    - match:
        secretKey: sensor-key.pem
        remoteRef:
          remoteKey: ACS_SENSOR_TLS_KEY
