apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: rhacs
spec:
  href: 'https://central-rhacs-operator.apps.hub.ocplab.com/'
  location: ApplicationMenu
  text: Advanced Cluster Security
  applicationMenu:
    section: Red Hat Applications
    imageURL: https://console-openshift-console.apps.hub.ocplab.com/static/assets/public/imgs/logos/redhat.svg
