apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: acm-observability
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: acm-observability
  objectBucketName: obc-open-cluster-management-observability-acm-observability
  storageClassName: noobaa.noobaa.io
