apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: eso-push-secrets
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: "eso-push-secret"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: thanos-object-storage
spec:
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: eso-push-secrets
      kind: SecretStore
  selector:
    secret:
      name: acm-observability
  template:
    stringData:
      thanos.yaml: |
        type: s3
        config:
          bucket: $BUCKET_NAME
          endpoint: s3.noobaa.svc
          insecure: true
          access_key: "{{ index . \"AWS_ACCESS_KEY_ID\" }}"
          secret_key: "{{ index . \"AWS_SECRET_ACCESS_KEY\" }}"
