apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: open-cluster-management-observability
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-read-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: thanos-object-storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: thanos-object-storage
    creationPolicy: Owner
    template:
      mergePolicy: Replace
      engineVersion: v2
      data:
        thanos.yaml: |
          type: s3
          config:
            bucket: acm-observability
            endpoint: s3.noobaa.svc
            insecure: true
            access_key: {{ .access_key }}
            secret_key: {{ .secret_key }}
  data:
    - secretKey: access_key
      remoteRef:
        key: acm-observability
        property: AWS_ACCESS_KEY_ID
    - secretKey: secret_key
      remoteRef:
        key: acm-observability
        property: AWS_SECRET_ACCESS_KEY
