apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-push-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-binding
subjects:
- kind: ServiceAccount
  name: eso-push-secret
- roleRef:
  kind: Role
  name: eso-role
  apiGroup: rbac.authorization.k8s.io
