{
 "title": "GitOps",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "cluster",
    "query": "label_values(argocd_cluster_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   { "name": "grouping", "query": "namespace,name,project" },
   {
    "name": "cluster",
    "label": "destination",
    "query": "label_values(argocd_cluster_info, server)"
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
  },
  {
   "title": "Clusters",
   "type": "singlestat",
   "description": "Number of clusters hosting Argo CD",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (cluster) (argocd_cluster_info{namespace=~\"$namespace\",cluster=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "description": "Total number of Argo CD instances",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (cluster,namespace) (argocd_cluster_info{namespace=~\"$namespace\",cluster=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "piechart",
   "description": "Application Health Status",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\",cluster=~\"$host\"}) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "piechart",
   "description": "Application Sync Status",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\",cluster=~\"$host\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",operation!=\"\",cluster=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "graph",
   "description": "Applications by host",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",cluster=~\"$host\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Application Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\",cluster=~\"$host\"}) by (cluster,namespace,health_status)",
       "legendFormat": "{{health_status}} ({{cluster}}/{{namespace}})"
      }
     ]
    },
    {
     "title": "Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\",cluster=~\"$host\"}) by (cluster,namespace,sync_status)",
       "legendFormat": "{{sync_status}} ({{cluster}}/{{namespace}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Activity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",dest_server=~\"$cluster\",cluster=~\"$host\"}[$interval]))) by ($grouping)",
       "legendFormat": "{{$grouping}}"
      }
     ]
    },
    {
     "title": "Sync Failures",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",phase=~\"Error|Failed\",dest_server=~\"$cluster\",cluster=~\"$host\"}[$interval]))) by ($grouping, phase)",
       "legendFormat": "{{phase}}: {{$grouping}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciliation Activity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_count{namespace=~\"$namespace\",dest_server=~\"$cluster\",cluster=~\"$host\"}[$interval])) by ($grouping)",
       "legendFormat": "{{$grouping}}"
      }
     ]
    },
    {
     "title": "Reconciliation Performance",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~\"$namespace\",cluster=~\"$host\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "K8s API Activity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(argocd_app_k8s_request_total{namespace=~\"$namespace\",server=~\"$cluster\",cluster=~\"$host\"}[$interval])) by (verb, resource_kind)",
       "legendFormat": "{{verb}} {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(workqueue_depth{namespace=~\"$namespace\",name=~\"app_.*\",cluster=~\"$host\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pending kubectl run",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(argocd_kubectl_exec_pending{namespace=~\"$namespace\",cluster=~\"$host\"}) by (command)",
       "legendFormat": "{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{container=\"argocd-application-controller\",namespace=~\"$namespace\",cluster=~\"$host\"}",
       "legendFormat": "{{cluster}}/{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{container=\"argocd-application-controller\",namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{cluster}}/{{namespace}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{container=\"argocd-application-controller\",namespace=~\"$namespace\",cluster=~\"$host\"}",
       "legendFormat": "{{cluster}}/{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Objects Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(argocd_cluster_api_resource_objects{namespace=~\"$namespace\",server=~\"$cluster\",cluster=~\"$host\"}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "API Resources Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "  sum(argocd_cluster_api_resources{namespace=~\"$namespace\",server=~\"$cluster\",cluster=~\"$host\"}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Cluster Events Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(argocd_cluster_events_total{namespace=~\"$namespace\",server=~\"$cluster\",cluster=~\"$host\"}[$interval])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Repo Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Requests (ls-remote)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\", namespace=~\"$namespace\",cluster=~\"$host\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Git Requests (checkout)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\", namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Git Fetch Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"fetch\", namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Git Ls-Remote Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"ls-remote\", namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{container=\"argocd-repo-server\",namespace=~\"$namespace\",cluster=~\"$host\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{container=\"argocd-repo-server\",namespace=~\"$namespace\",cluster=~\"$host\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{container=\"argocd-server\",namespace=~\"$namespace\",cluster=~\"$host\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{container=\"argocd-server\",namespace=~\"$namespace\",cluster=~\"$host\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{container=\"argocd-server\", quantile=\"1\", namespace=~\"$namespace\",cluster=~\"$host\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 115 }, "content": "#### gRPC Services:" },
    {
     "title": "ApplicationService Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{container=\"argocd-server\",grpc_service=\"application.ApplicationService\",namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "ClusterService Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{container=\"argocd-server\",grpc_service=\"cluster.ClusterService\",namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "ProjectService Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{container=\"argocd-server\",grpc_service=\"project.ProjectService\",namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "RepositoryService Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{container=\"argocd-server\",grpc_service=\"repository.RepositoryService\",namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "SessionService Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{container=\"argocd-server\",grpc_service=\"session.SessionService\",namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "VersionService Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{container=\"argocd-server\",grpc_service=\"version.VersionService\",namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "AccountService Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{container=\"argocd-server\",grpc_service=\"account.AccountService\",namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    },
    {
     "title": "SettingsService Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{container=\"argocd-server\",grpc_service=\"settings.SettingsService\",namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (grpc_code, grpc_method)",
       "legendFormat": "{{grpc_code}},{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by result",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(argocd_redis_request_total{namespace=~\"$namespace\",cluster=~\"$host\"}[$__rate_interval])) by (failed)"
      }
     ]
    }
   ]
  }
 ]
}